name: Build Quarkus Native Image and Container

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
permissions:
  contents: write

jobs:
  build-and-package-native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: chmod
        run: chmod +x ./mvnw

      - name: Build with Maven (compile)
        run: ./mvnw clean compile

      - name: ldd version
        run: ldd --version

      - name: Build native image
        run: ./mvnw package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: Upload native binary to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*-runner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Docker related steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set repository name env
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}
          # Build the Docker image
          docker build -f src/main/docker/Dockerfile.native-micro -t $IMAGE_NAME:${{ github.ref_name }} -t $IMAGE_NAME:latest .
          # Push the Docker image with tag
          docker push $IMAGE_NAME:${{ github.ref_name }}
          # Push the Docker image with latest tag
          docker push $IMAGE_NAME:latest

      - name: Save Docker image for Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.ref_name }} > ${{ env.REPO_NAME }}-${{ github.ref_name }}.tar
          gzip ${{ env.REPO_NAME }}-${{ github.ref_name }}.tar

      - name: Upload Docker image to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.REPO_NAME }}-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows-native:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        id: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Verify Java and GraalVM installation
        shell: cmd
        run: |
          echo "GraalVM Home from output: ${{ steps.setup-graalvm.outputs.graalvm-home }}"
          echo "Setting environment variables..."
          set "JAVA_HOME=${{ steps.setup-graalvm.outputs.graalvm-home }}"
          set "GRAALVM_HOME=${{ steps.setup-graalvm.outputs.graalvm-home }}"
          echo "JAVA_HOME=%JAVA_HOME%"
          echo "GRAALVM_HOME=%GRAALVM_HOME%"
          echo "Verifying Java installation:"
          "%JAVA_HOME%\bin\java" -version
          echo "Verifying native-image:"
          "%GRAALVM_HOME%\bin\native-image" --version
        env:
          JAVA_HOME: ${{ steps.setup-graalvm.outputs.graalvm-home }}
          GRAALVM_HOME: ${{ steps.setup-graalvm.outputs.graalvm-home }}

      - name: Build with Maven (compile)
        shell: cmd
        run: |
          echo "Setting up environment for compilation..."
          set "JAVA_HOME=${{ steps.setup-graalvm.outputs.graalvm-home }}"
          set "GRAALVM_HOME=${{ steps.setup-graalvm.outputs.graalvm-home }}"
          set "PATH=${{ steps.setup-graalvm.outputs.graalvm-home }}\bin;%PATH%"
          echo "Using JAVA_HOME: %JAVA_HOME%"
          echo "Starting Maven compilation..."
          .\mvnw.cmd clean compile
        env:
          JAVA_HOME: ${{ steps.setup-graalvm.outputs.graalvm-home }}
          GRAALVM_HOME: ${{ steps.setup-graalvm.outputs.graalvm-home }}

      - name: Build Windows native image with MSVC
        shell: cmd
        run: |
          echo "Initializing MSVC environment..."
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo "Setting up Java environment..."
          set "JAVA_HOME=${{ steps.setup-graalvm.outputs.graalvm-home }}"
          set "GRAALVM_HOME=${{ steps.setup-graalvm.outputs.graalvm-home }}"
          set "PATH=${{ steps.setup-graalvm.outputs.graalvm-home }}\bin;%PATH%"
          echo "Environment check:"
          echo "JAVA_HOME=%JAVA_HOME%"
          echo "GRAALVM_HOME=%GRAALVM_HOME%"
          echo "Starting native image build..."
          .\mvnw.cmd package -Pnative -DskipTests -Dquarkus.native.additional-build-args="--verbose,--no-fallback" -Dquarkus.native.native-image-xmx=4g
        env:
          JAVA_HOME: ${{ steps.setup-graalvm.outputs.graalvm-home }}
          GRAALVM_HOME: ${{ steps.setup-graalvm.outputs.graalvm-home }}

      - name: Upload Windows native binary to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*-runner.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
